clone:
  depth: 1
definitions:
  caches:
    haxe: ~/haxe
pipelines:
  branches:
    main:
      - parallel:
          - step:
              name: HashLink
              caches: [haxe]
              image: cedxbelin/haxe.hl
              script:
                - lix download
                - haxe test_hl.hxml
          - step:
              name: Java
              caches: [haxe]
              image: cedxbelin/haxe.java
              script:
                - lix download
                - haxe test_java.hxml
          - step:
              name: JavaScript
              caches: [haxe]
              image: cedxbelin/haxe.node
              script:
                - lix download
                - haxe test_js.hxml
          - step:
              name: PHP
              caches: [haxe]
              image: cedxbelin/haxe.php
              script:
                - lix download
                - haxe test_php.hxml
