<?php
/**
 * Generated by Haxe 4.1.5
 */

namespace which;

use \php\Boot;

/**
 * Provides helper methods for handling `Finder` instances.
 */
class FinderTools {
	/**
	 * Finds the instances of the specified `command` in the system path.
	 * 
	 * @param string $command
	 * @param mixed $options
	 * 
	 * @return FinderStream
	 */
	public static function which ($command, $options = null) {
		return new FinderStream($command, new Finder($options));
	}
}

Boot::registerClass(FinderTools::class, 'which.FinderTools');
