<?php
/**
 * Generated by Haxe 4.1.4
 */

namespace which;

use \php\_Boot\HxAnon;
use \php\Boot;
use \tink\streams\StreamObject;

/**
 * Provides static extensions.
 */
class FinderTools {
	/**
	 * Finds the instances of the specified `command` in the system path.
	 * 
	 * @param string $command
	 * @param mixed $options
	 * 
	 * @return StreamObject
	 */
	public static function which ($command, $options = null) {
		return (new Finder(new HxAnon($options)))->find($command);
	}
}

Boot::registerClass(FinderTools::class, 'which.FinderTools');
