<?php
/**
 * Generated by Haxe 4.1.1
 */

namespace which;

use \php\Boot;
use \sys\io\File;
use \haxe\Json;

/**
 * Provides the version number of this package.
 */
class Version {
	/**
	 * Reads the version number of this package from the `haxelib.json` file.
	 * 
	 * @return string
	 */
	public static function getHaxelibVersion () {
		try {
			return Boot::dynamicField(Json::phpJsonDecode(File::getContent("haxelib.json")), 'version');
		} catch(\Throwable $_g) {
			return "0.0.0";
		}
	}
}

Boot::registerClass(Version::class, 'which.Version');
