name: continuous-integration
on: push

jobs:
  test:
    runs-on: ${{matrix.target == 'hl' && 'windows-latest' || 'ubuntu-latest'}}
    strategy:
      matrix:
        target: [hl, java, js, php]
    steps:
      - name: Fetch sources
        uses: actions/checkout@v4
      - name: Set up Lix
        uses: lix-pm/setup-lix@master
      - name: Set up HashLink
        if: matrix.target == 'hl'
        uses: cedx/setup-hashlink@v4
      - name: Set up Java
        if: matrix.target == 'java'
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Set up Node.js
        if: matrix.target == 'js'
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Set up PHP
        if: matrix.target == 'php'
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          extensions: curl, intl, mbstring, simplexml
          php-version: 8.3
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/haxe
            ~/AppData/Roaming/haxe
          key: haxe-${{runner.os}}-lix-${{hashFiles('.haxerc', 'haxe_libraries/*.hxml')}}
          restore-keys: haxe-${{runner.os}}-lix-
      - name: Install dependencies
        run: lix download
      - name: Run tests
        run: haxe test_${{matrix.target}}.hxml
